package app

// ⚠️ 由 sync_deprecated.py 自动生成 — 来源: Unciv.jar DeprecatedUniqueType
// 每次更新 Unciv 后运行: python3 sync_deprecated.py

var deprecatedRules = []deprecatedRule{
	{Since: "4.21.1", Severity: "warning", Pattern: "Receive triple Gold from Barbarian encampments and pillaging Cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Doubles Gold given to enemy if city is captured"},
	{Since: "4.21.1", Severity: "warning", Pattern: "upon declaring war with a major Civilization"},
	{Since: "4.21.1", Severity: "warning", Pattern: "May Paradrop up to [positiveAmount] tiles from inside friendly territory"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Quantity of strategic resources produced by the empire +[relativeAmount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double quantity of [resource] produced"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% maintenance cost for buildings [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Remove extra unhappiness from annexed cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% Strength when stacked with [mapUnitFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when between [amount] and [amount] Happiness"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when above [amount] Happiness"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when below [amount] Happiness"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden until [amount] social policy branches have been completed"},
	{Since: "4.21.1", Severity: "warning", Pattern: "New [baseUnitFilter] units start with [amount] Experience [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can spend Gold to annex or puppet a City-State that has been your ally for [amount] turns."},
	{Since: "4.21.1", Severity: "warning", Pattern: "Defense bonus when embarked"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden when [victoryType] Victory is disabled"},
	{Since: "4.21.1", Severity: "warning", Pattern: "getSetOfHiddenToUsers"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden when religion is disabled"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden when espionage is disabled"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit gains [amount] movement"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit loses the [promotion] promotion"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit gains the [promotion] promotion"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit upgrades for free including special upgrades"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Heal this unit by [positiveAmount] HP"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit takes [positiveAmount] damage"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit gains [amount] XP"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit upgrades for free"},
	{Since: "4.21.1", Severity: "warning", Pattern: "This Unit loses [amount] movement"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Neighboring tiles except [simpleTerrain] will convert to [baseTerrain/terrainFeature]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in tiles adjacent to [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in tiles not adjacent to [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Constructing it will take over the tiles around it and assign them to your closest city"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Damage is ignored when determining unit Strength"},
	{Since: "4.21.1", Severity: "warning", Pattern: "May withdraw before melee ([amount]%)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "before [amount] turns"},
	{Since: "4.21.1", Severity: "warning", Pattern: "after [amount] turns"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides a sum of gold each time you spend a Great Person"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] whenever a Great Person is expended"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gain [amount] [stat] (modified by game speed)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when above [amount] [stat/resource] (modified by game speed)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when below [amount] [stat/resource] (modified by game speed)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when between [amount] and [amount] [stat/resource] (modified by game speed)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] when a city adopts this religion for the first time (modified by game speed)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Grants 500 Gold to the first civilization to discover it"},
	{Since: "4.21.1", Severity: "warning", Pattern: "100 Gold for discovering a Natural Wonder (bonus enhanced to 500 Gold if first to discover it)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Requires a [buildingFilter] in all cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Requires a [buildingFilter] in at least [positiveAmount] cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can only be built [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "upon discovering [tech]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+30% Strength when fighting City-State units and cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "with [amount] to [amount] neighboring [tileFilter] [tileFilter] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in [tileFilter] [tileFilter] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden after generating a Great Prophet"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% tile improvement construction time"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can [action] [amount] times"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[baseUnitFilter] units built [cityFilter] can [action] [amount] extra times"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Receive free [unit] when you discover [tech]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Unhappiness from number of Cities doubled"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Normal vision when embarked"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can start an [amount]-turn golden age"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can construct [improvementName]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Costs [amount] gold per turn when in your territory"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides 1 happiness per 2 additional social policies adopted"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double Happiness from Natural Wonders"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available after [amount] turns"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden before founding a Pantheon"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Hidden after founding a Pantheon"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides [stats] per turn"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides [stats] [cityFilter] per turn"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides [amount] Happiness"},
	{Since: "4.21.1", Severity: "error", Pattern: "Enemy land units must spend 1 extra movement point when inside your territory (obsolete upon Dynamite)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can construct [improvementName] if it hasn\\'t used other actions yet"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Production to science conversion in cities increased by 33%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Tile yields from Natural Wonders doubled"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables conversion of city production to gold"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables conversion of city production to science"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Units fight as though they were at full strength even when damaged"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Strength if within [amount2] tiles of a [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] with [resource]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can only be built in annexed cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Embarked units can defend themselves"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Units pay only 1 movement point to disembark"},
	{Since: "4.21.1", Severity: "warning", Pattern: "67% chance to earn 25 Gold and recruit a Barbarian unit from a conquered encampment"},
	{Since: "4.21.1", Severity: "warning", Pattern: "50% chance of capturing defeated Barbarian naval units and earning 25 Gold"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Eliminates combat penalty for attacking from the sea"},
	{Since: "4.21.1", Severity: "warning", Pattern: "6 tiles in every direction always visible"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Resistant to nukes"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can be destroyed by nukes"},
	{Since: "4.21.1", Severity: "warning", Pattern: "if this city has at least [amount] specialists"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in cities where this religion has at least [amount] followers"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% attack strength to all [mapUnitFilter] units for [amount2] turns"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables embarked units to enter ocean tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can embark and move over Coasts and Oceans immediately"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% unhappiness from population [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% unhappiness from specialists [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% great person generation [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gold from all trade routes +25%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] in cities with [amount] or more population"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Incompatible with [policy/tech/promotion]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Not displayed as an available construction without [buildingName/tech/resource/policy]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Unlocked with [buildingName/tech/era/policy]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Requires [buildingName/tech/era/policy]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Cannot be built with [buildingName]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Requires a [buildingName] in this city"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Bonus for units in 2 tile radius 15%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from every Wonder"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from every [buildingFilter] in cities where this religion has at least [amount] followers"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+25% Production towards any buildings that already exist in the Capital"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% of food is carried over after population increases"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% of food is carried over [cityFilter] after population increases"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount] Culture cost of natural border growth [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% Culture cost of acquiring tiles [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% cost of natural border growth"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% Gold cost of acquiring tiles [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stat] cost of purchasing [baseUnitFilter] units in cities [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% attacking strength for cities with garrisoned units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Population loss from nuclear attacks -[amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Natural religion spread [cityFilter] with [tech/policy]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount] HP when healing in [tileFilter] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Melee units pay no movement cost to pillage"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Heal adjacent units for an additional 15 HP per turn"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Deal [amount] damage to adjacent enemy units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Golden Age length increased by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Defensive Strength for cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Attacking Strength for cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength for [mapUnitFilter] units which have another [mapUnitFilter] unit in an adjacent tile"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gold cost of upgrading [baseUnitFilter] units reduced by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double gold from Great Merchant trade missions"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Defensive buildings in all cities are 25% more effective"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Maintenance on roads & railroads reduced by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% maintenance cost for buildings [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount] happiness from each type of luxury resource"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Culture cost of adopting new Policies reduced by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Culture cost of adopting new policies"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Quantity of Resources gifted by City-States increased by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "City-State Influence degrades [amount]% slower"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Happiness from Luxury Resources gifted by City-States increased by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% [stat] from every [tileFilter/specialist/buildingName]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% yield from every [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] per turn from cities before [tech/policy]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "50% of excess happiness added to culture towards policies"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Not displayed as an available construction unless [buildingName] is built"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% food consumption by specialists [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Cannot enter ocean tiles until Astronomy"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Cannot be built on [tileFilter] tiles until [tech] is discovered"},
	{Since: "4.21.1", Severity: "warning", Pattern: "May buy [baseUnitFilter] units for [amount] [stat] [cityFilter] starting from the [era] at an increasing price ([amount])"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] on [tileFilter] tiles once [tech] is discovered"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] once [tech] is discovered"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Deal 30 damage to adjacent enemy units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides a free [buildingName] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% [stat] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% [stat] in all cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% [stat] while the empire is happy"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Immediately creates the cheapest available cultural building in each of your first [amount] cities for free"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Immediately creates a [buildingName] in each of your first [amount] cities for free"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Strength when attacking"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Strength when defending"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength when defending vs [mapUnitFilter] units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[mapUnitFilter] units deal +[amount]% damage"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+10% Strength for all units during Golden Age"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% defence in [tileFilter] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Strength in [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength for [mapUnitFilter] units in [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+15% Combat Strength for all units when attacking Cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount] Movement for all [mapUnitFilter] units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+1 Movement for all units during Golden Age"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount] Sight for all [mapUnitFilter] units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount] Visibility Range"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Spread Religion Strength for [mapUnitFilter] units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Production when constructing [baseUnitFilter] units [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Production when constructing [stat] buildings"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Production when constructing [constructionFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Production when constructing a [buildingName]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Production when constructing [constructionFilter] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double movement in coast"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double movement rate through Forest and Jungle"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double movement in Snow, Tundra and Hills"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Strength"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% Strength"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Strength vs [combatantFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% Strength vs [combatantFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% Combat Strength"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Increases embarked movement +1"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+1 Movement for all embarked units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Unhappiness from population decreased by [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Unhappiness from population decreased by [amount]% [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% growth [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount]% growth [cityFilter] when not at war"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% [mapUnitFilter] unit maintenance costs"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-[amount]% unit upkeep costs"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from every specialist"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] if this city has at least [amount] specialists"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Bonus XP gain"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[mapUnitFilter] units gain [amount]% more Experience from combat"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% maintenance costs for [mapUnitFilter] units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount] Visibility Range"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+[amount] Sight for all [mapUnitFilter] units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can build improvements on tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+1 happiness from each type of luxury resource"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Science gained from research agreements +50%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-33% unit upkeep costs"},
	{Since: "4.21.1", Severity: "warning", Pattern: "-50% food consumption by specialists"},
	{Since: "4.21.1", Severity: "warning", Pattern: "+50% attacking strength for cities with garrisoned units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "(Lkotlin/jvm/internal/DefaultConstructorMarker;)V"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Receive [+200]% Gold from Barbarian encampments and pillaging Cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100]% Gold given to enemy if city is captured <in this city>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "upon declaring war on [Major] Civilizations"},
	{Since: "4.21.1", Severity: "warning", Pattern: "May Paradrop to [Land] tiles up to [positiveAmount] tiles away <in [{Friendly} {Land}] tiles>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% [Strategic] resource production"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100]% [resource] resource production"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% maintenance cost for [all] buildings [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Removes extra unhappiness from annexed cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% Strength <when stacked with a [mapUnitFilter] unit>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when between [amount] and [amount] [Happiness]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when above [amount] [Happiness]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when below [amount] [Happiness]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Unavailable <when number of [Completed Policy branches] is less than [amount]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "New [baseUnitFilter] units start with [amount] XP [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can spend Gold to annex or puppet a City-State that has been your Ally for [amount] turns"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100]% Strength <when defending> <when [Embarked]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <when [victoryType] Victory is enabled>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <when religion is enabled>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <when espionage is enabled>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "for [civFilter] Civilizations"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] gains [amount] movement"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] loses the [promotion] promotion"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] gains the [promotion] promotion"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] upgrades for free including special upgrades"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] heals [positiveAmount] HP"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] takes [positiveAmount] damage"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] gains [amount] XP"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] upgrades for free"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[This Unit] loses [amount] movement"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Neighboring tiles will convert to [baseTerrain/terrainFeature] <in tiles without [simpleTerrain]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in tiles adjacent to [tileFilter] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in tiles not adjacent to [tileFilter] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gain control over [all] tiles in a [1]-tile radius"},
	{Since: "4.21.1", Severity: "warning", Pattern: "No damage penalty for wounded units"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Withdraws before melee combat <with [amount]% chance>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "before turn number [amount]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "after turn number [amount]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gain [100] [Gold] <upon expending a [Great Person] unit> <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gain [amount] [stat] <upon expending a [Great Person] unit> <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gain [amount] [stat] <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when above [amount] [stat/resource] <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when below [amount] [stat/resource] <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "when between [amount] and [amount] [stat/resource] <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] when a city adopts this religion for the first time <(modified by game speed)>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Grants [+500 Gold] to the first civilization to discover it"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100 Gold] for discovering a Natural Wonder (bonus enhanced to [+500 Gold] if first to discover it)"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <if [buildingFilter] is constructed in all [non-[Puppeted]] cities>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <if [buildingFilter] is constructed in at least [positiveAmount] of [All] cities>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can only be built <in [cityFilter] cities>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "upon discovering [tech] technology"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+30]% Strength <vs [City-States]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "with [amount] to [amount] neighboring [{tileFilter} {tileFilter}] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in [{tileFilter} {tileFilter}] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Unavailable <after generating a Great Prophet>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% construction time for [All] improvements"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can Spread Religion <[amount] times> <after which this unit is consumed>\\\" OR \\\"Can remove other religions from cities <in [Friendly] tiles> <once> <after which this unit is consumed>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "All newly-trained [baseUnitFilter] units [cityFilter] receive the [Devout] promotion"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Free [unit] appears <upon discovering [tech]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100]% unhappiness from the number of cities"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+1] Sight <for [Embarked] units>\\\" OR \\\"[+1] Sight <when [Embarked]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Empire enters a [amount]-turn Golden Age <by consuming this unit>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can instantly construct a [improvementName] improvement <by consuming this unit>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Costs [amount] [stats] per turn when in your territory"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+1 Happiness] per [2] social policies adopted"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+1 Happiness] for every known Natural Wonder"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <after [amount] turns>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <before founding a Pantheon>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount Happiness]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enemy [Land] units must spend [1] extra movement points when inside your territory <before discovering [Dynamite]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can construct [improvementName] <if it hasn\\'t used other actions yet>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Production to [Science] conversion in cities changed by [33]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100]% Yield from every [Natural Wonder]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables conversion of city production to [Gold]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables conversion of city production to [Science]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Damage is ignored when determining unit Strength <for [All] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength <within [amount2] tiles of a [tileFilter]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] <with [resource]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can only be built <in [Annexed] cities>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Defense bonus when embarked <for [All] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[1] Movement point cost to disembark <for [All] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "When conquering an encampment, earn [25] Gold and recruit a Barbarian unit <with [67]% chance>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "When defeating a [{Barbarian} {Water}] unit, earn [25] Gold and recruit it <with [50]% chance>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Eliminates combat penalty for attacking across a coast"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[25]% Chance to be destroyed by nukes"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[50]% Chance to be destroyed by nukes"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in cities with at least [amount] [Specialists]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "in cities with at least [amount] [Followers of the Majority Religion]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength <when attacking> <for [mapUnitFilter] units> <for [amount2] turns>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables [Embarked] units to enter ocean tiles <starting from the [Ancient era]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Enables embarkation for land units <starting from the [Ancient era]>\\\", \\\"Enables [All] units to enter ocean tiles <starting from the [Ancient era]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% Unhappiness from [Population] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% Unhappiness from [Specialists] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[relativeAmount]% Great Person generation [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+25]% [Gold] from Trade Routes"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] <in cities with at least [amount] [Population]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <before adopting [policy/tech/promotion]>\\\" OR \\\"Only available <before discovering [policy/tech/promotion]>\\\" OR \\\"Only available <for units without [policy/tech/promotion]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <in cities without a [buildingName]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Only available <in cities with a [buildingName]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+15]% Strength bonus for [Military] units within [2] tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from every [Wonder]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from every [buildingFilter] <in cities where this religion has at least [amount] followers>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+25]% Production towards any buildings that already exist in the Capital"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Food is carried over after population increases [in this city]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Food is carried over after population increases [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Culture cost of natural border growth [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Culture cost of natural border growth [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Culture cost of natural border growth [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Gold cost of acquiring tiles [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stat] cost of purchasing [baseUnitFilter] units [amount]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength for cities <with a garrison> <when attacking>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Population loss from nuclear attacks [-amount]% [in this city]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Natural religion spread [cityFilter] <after discovering [tech/policy]>\\\" OR \\\"[amount]% Natural religion spread [cityFilter] <after adopting [tech/policy]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount] HP when healing <in [tileFilter] tiles>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "No movement cost to pillage <for [Melee] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "All adjacent units heal [+15] HP when healing"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Adjacent enemy units ending their turn take [amount] damage"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Golden Age length"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength for cities <when defending>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength for cities <when attacking>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength <for [mapUnitFilter] units> <when adjacent to a [mapUnitFilter] unit>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Gold cost of upgrading <for [baseUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+100]% Gold from Great Merchant trade missions"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+25]% City Strength from defensive buildings"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% maintenance on road & railroads"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% maintenance cost for buildings [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount] Happiness from each type of luxury resource"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Culture cost of adopting new Policies"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Culture cost of adopting new Policies"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% resources gifted by City-States"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% City-State Influence degradation"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Happiness from luxury resources gifted by City-States"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% [stat] from every [tileFilter/specialist/buildingName]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Yield from every [tileFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] [in all cities] <before discovering [tech]>\\\" OR \\\"[stats] [in all cities] <before adopting [policy]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[50]% of excess happiness converted to [Culture]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Not displayed as an available construction without [buildingName]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Food consumption by specialists [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Cannot enter ocean tiles <before discovering [Astronomy]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Cannot be built on [tileFilter] tiles <before discovering [tech]>"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.9 - removed 3.19.3"},
	{Since: "4.21.1", Severity: "warning", Pattern: "May buy [baseUnitFilter] units for [amount] [stat] [cityFilter] at an increasing price ([amount]) <starting from the [era]>"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.10 - removed 3.18.19"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from [tileFilter] tiles <after discovering [tech]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] <after discovering [tech]>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Adjacent enemy units ending their turn take [30] damage"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.7 - removed 3.18.19"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Gain a free [buildingName] [cityFilter]"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.10 - removed 3.18.18"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% [stat] [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% [stat] [in all cities]"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.1 - removed 3.18.18"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% [stat] [in all cities] <while the empire is happy>"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.16.15 - removed 3.18.4"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides the cheapest [stat] building in your first [amount] cities for free"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Provides a [buildingName] in your first [amount] cities for free"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.5 - removed 3.18.5"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength <when attacking>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength <when defending>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength <when defending> <vs [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+10]% Strength <for [All] units> <during a Golden Age>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength <when fighting in [tileFilter] tiles> <when defending>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength <when fighting in [tileFilter] tiles>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Strength <for [mapUnitFilter] units> <when fighting in [tileFilter] tiles>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+15]% Strength <for [All] units> <vs cities> <when attacking>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount] Movement <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+1] Movement <for [All] units> <during a Golden Age>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount] Sight <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Spread Religion Strength <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.10 - removed 3.18.5"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Production when constructing [baseUnitFilter] units [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Production when constructing [stat] buildings [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Production when constructing [constructionFilter] buildings [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Production when constructing [buildingName] buildings [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% Production when constructing [constructionFilter] buildings [cityFilter]"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.1 - removed 3.17.13"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double movement in [Coast]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Double movement in [terrainFilter]"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.17.3 - removed 3.17.13"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Strength"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% Strength <vs [combatantFilter] units>\\\" OR \\\"[+amount]% Strength <vs cities>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% Strength <vs [combatantFilter] units>\\\" OR \\\"[+amount]% Strength <vs cities>"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.16.11 - removed 3.17.11"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+1] Movement <for [Embarked] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% unhappiness from population [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% unhappiness from population [cityFilter]"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.16.14 - removed 3.17.11"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% growth [cityFilter]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount]% growth [cityFilter] <when not at war>"},
	{Since: "4.21.1", Severity: "error", Pattern: "as of 3.16.16 - removed 3.17.11"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-amount]% maintenance costs <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% maintenance costs <for [All] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] from every specialist [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[stats] <if this city has at least [amount] specialists>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% XP gained from combat"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% XP gained from combat <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[amount]% maintenance costs <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount] Sight"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+amount] Sight <for [mapUnitFilter] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Can build [Land] improvements on tiles"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+1] Happiness from each type of luxury resource"},
	{Since: "4.21.1", Severity: "warning", Pattern: "Science gained from research agreements [+50]%"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-33]% maintenance costs <for [All] units>"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[-50]% Food consumption by specialists [in all cities]"},
	{Since: "4.21.1", Severity: "warning", Pattern: "[+50]% Strength for cities <with a garrison> <when attacking>"},
}
