// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AnalyzeConflicts():Promise<Array<app.ConflictReport>>;

export function ArchiveSave(arg1:string):Promise<string>;

export function AutoDetectUncivPath():Promise<string>;

export function BackupMod(arg1:string,arg2:string):Promise<string>;

export function BuildDownloadURL(arg1:string,arg2:app.ProxyConfig):Promise<string>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckDeprecated():Promise<Array<app.DiagIssue>>;

export function CheckModUpdates():Promise<Array<app.ModUpdateInfo>>;

export function CheckSelfUpdate():Promise<app.SelfUpdateInfo>;

export function CleanupModBackupMeta():Promise<void>;

export function CleanupTempFile(arg1:string):Promise<void>;

export function CompareModSnapshot(arg1:string):Promise<Array<app.MultiplayerDiff>>;

export function ConvertWesnothMap(arg1:string):Promise<string>;

export function DeleteBackup(arg1:string):Promise<void>;

export function DeleteMap(arg1:string):Promise<void>;

export function DeleteMod(arg1:string):Promise<void>;

export function DeleteSave(arg1:string):Promise<void>;

export function DeleteSaveArchive(arg1:string):Promise<void>;

export function DiagnoseMods():Promise<Array<app.DiagIssue>>;

export function DownloadAllUpdates(arg1:Array<app.ModUpdateInfo>):Promise<Array<string>>;

export function DownloadModUpdate(arg1:string):Promise<string>;

export function DownloadSelfUpdate(arg1:string):Promise<string>;

export function ExportLogFile():Promise<string>;

export function ExportModSnapshot():Promise<string>;

export function ExtractMod(arg1:string,arg2:string):Promise<string>;

export function FetchReadme(arg1:string,arg2:string):Promise<string>;

export function FetchReleases(arg1:string):Promise<Array<app.GHRelease>>;

export function GetAppConfig():Promise<app.AppConfig>;

export function GetDownloadList():Promise<Array<app.DownloadTask>>;

export function GetLogFiles():Promise<Array<string>>;

export function GetUMMVersion():Promise<string>;

export function GetUncivInfo():Promise<Record<string, any>>;

export function GetUncivVersion():Promise<string>;

export function ImportFile(arg1:string):Promise<string>;

export function InstallSelfUpdate():Promise<Record<string, boolean>>;

export function IsUncivRunning():Promise<boolean>;

export function LaunchUnciv():Promise<void>;

export function ListBackups():Promise<Array<app.ModBackup>>;

export function ListSaveArchives():Promise<Array<app.SaveArchive>>;

export function OpenSnapshotFolder():Promise<string>;

export function PauseDownload(arg1:string):Promise<void>;

export function ReadCrashReport():Promise<app.CrashInfo>;

export function ReadLocalModCache():Promise<Array<app.OnlineMod>>;

export function ReadLogFile(arg1:string):Promise<string>;

export function ReadModPreview(arg1:string):Promise<string>;

export function ReadModReadme(arg1:string):Promise<string>;

export function RemoveDownload(arg1:string):Promise<void>;

export function RenameMap(arg1:string,arg2:string):Promise<string>;

export function RestoreBackup(arg1:string):Promise<void>;

export function RestoreSaveArchive(arg1:string):Promise<string>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RetryDownload(arg1:string):Promise<void>;

export function SaveAppConfig(arg1:app.AppConfig):Promise<void>;

export function SaveClipboardMap(arg1:string,arg2:string):Promise<string>;

export function ScanMaps():Promise<Array<app.MapInfo>>;

export function ScanMods():Promise<Array<app.ModInfo>>;

export function ScanSaves():Promise<Array<app.SaveInfo>>;

export function SearchOnlineMods(arg1:string):Promise<Array<app.OnlineMod>>;

export function SelectUncivDir():Promise<string>;

export function SetUncivPath(arg1:string):Promise<void>;

export function SetZoomLevel(arg1:number):Promise<number>;

export function StartDownload(arg1:string,arg2:string):Promise<string>;

export function StartDownloadWithMirror(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TestMirrorsLatency():Promise<Record<string, number>>;

export function TranslateText(arg1:string):Promise<string>;

export function ValidateDownloadURL(arg1:string):Promise<string>;

export function ValidateUncivPath(arg1:string):Promise<app.UncivInfo>;
