// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeConflicts() {
  return window['go']['app']['App']['AnalyzeConflicts']();
}

export function ArchiveSave(arg1) {
  return window['go']['app']['App']['ArchiveSave'](arg1);
}

export function AutoDetectUncivPath() {
  return window['go']['app']['App']['AutoDetectUncivPath']();
}

export function BackupMod(arg1, arg2) {
  return window['go']['app']['App']['BackupMod'](arg1, arg2);
}

export function BuildDownloadURL(arg1, arg2) {
  return window['go']['app']['App']['BuildDownloadURL'](arg1, arg2);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CheckDeprecated() {
  return window['go']['app']['App']['CheckDeprecated']();
}

export function CheckModUpdates() {
  return window['go']['app']['App']['CheckModUpdates']();
}

export function CheckSelfUpdate() {
  return window['go']['app']['App']['CheckSelfUpdate']();
}

export function CleanupModBackupMeta() {
  return window['go']['app']['App']['CleanupModBackupMeta']();
}

export function CleanupTempFile(arg1) {
  return window['go']['app']['App']['CleanupTempFile'](arg1);
}

export function CompareModSnapshot(arg1) {
  return window['go']['app']['App']['CompareModSnapshot'](arg1);
}

export function ConvertWesnothMap(arg1) {
  return window['go']['app']['App']['ConvertWesnothMap'](arg1);
}

export function DeleteBackup(arg1) {
  return window['go']['app']['App']['DeleteBackup'](arg1);
}

export function DeleteMap(arg1) {
  return window['go']['app']['App']['DeleteMap'](arg1);
}

export function DeleteMod(arg1) {
  return window['go']['app']['App']['DeleteMod'](arg1);
}

export function DeleteSave(arg1) {
  return window['go']['app']['App']['DeleteSave'](arg1);
}

export function DeleteSaveArchive(arg1) {
  return window['go']['app']['App']['DeleteSaveArchive'](arg1);
}

export function DiagnoseMods() {
  return window['go']['app']['App']['DiagnoseMods']();
}

export function DownloadAllUpdates(arg1) {
  return window['go']['app']['App']['DownloadAllUpdates'](arg1);
}

export function DownloadModUpdate(arg1) {
  return window['go']['app']['App']['DownloadModUpdate'](arg1);
}

export function DownloadSelfUpdate(arg1) {
  return window['go']['app']['App']['DownloadSelfUpdate'](arg1);
}

export function ExportModSnapshot() {
  return window['go']['app']['App']['ExportModSnapshot']();
}

export function ExtractMod(arg1, arg2) {
  return window['go']['app']['App']['ExtractMod'](arg1, arg2);
}

export function FetchReadme(arg1, arg2) {
  return window['go']['app']['App']['FetchReadme'](arg1, arg2);
}

export function FetchReleases(arg1) {
  return window['go']['app']['App']['FetchReleases'](arg1);
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetDownloadList() {
  return window['go']['app']['App']['GetDownloadList']();
}

export function GetUMMVersion() {
  return window['go']['app']['App']['GetUMMVersion']();
}

export function GetUncivInfo() {
  return window['go']['app']['App']['GetUncivInfo']();
}

export function GetUncivVersion() {
  return window['go']['app']['App']['GetUncivVersion']();
}

export function ImportFile(arg1) {
  return window['go']['app']['App']['ImportFile'](arg1);
}

export function InstallSelfUpdate() {
  return window['go']['app']['App']['InstallSelfUpdate']();
}

export function IsUncivRunning() {
  return window['go']['app']['App']['IsUncivRunning']();
}

export function LaunchUnciv() {
  return window['go']['app']['App']['LaunchUnciv']();
}

export function ListBackups() {
  return window['go']['app']['App']['ListBackups']();
}

export function ListSaveArchives() {
  return window['go']['app']['App']['ListSaveArchives']();
}

export function OpenSnapshotFolder() {
  return window['go']['app']['App']['OpenSnapshotFolder']();
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function ReadCrashReport() {
  return window['go']['app']['App']['ReadCrashReport']();
}

export function ReadLocalModCache() {
  return window['go']['app']['App']['ReadLocalModCache']();
}

export function ReadModPreview(arg1) {
  return window['go']['app']['App']['ReadModPreview'](arg1);
}

export function ReadModReadme(arg1) {
  return window['go']['app']['App']['ReadModReadme'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['app']['App']['RemoveDownload'](arg1);
}

export function RenameMap(arg1, arg2) {
  return window['go']['app']['App']['RenameMap'](arg1, arg2);
}

export function RestoreBackup(arg1) {
  return window['go']['app']['App']['RestoreBackup'](arg1);
}

export function RestoreSaveArchive(arg1) {
  return window['go']['app']['App']['RestoreSaveArchive'](arg1);
}

export function ResumeDownload(arg1) {
  return window['go']['app']['App']['ResumeDownload'](arg1);
}

export function RetryDownload(arg1) {
  return window['go']['app']['App']['RetryDownload'](arg1);
}

export function SaveAppConfig(arg1) {
  return window['go']['app']['App']['SaveAppConfig'](arg1);
}

export function SaveClipboardMap(arg1, arg2) {
  return window['go']['app']['App']['SaveClipboardMap'](arg1, arg2);
}

export function ScanMaps() {
  return window['go']['app']['App']['ScanMaps']();
}

export function ScanMods() {
  return window['go']['app']['App']['ScanMods']();
}

export function ScanSaves() {
  return window['go']['app']['App']['ScanSaves']();
}

export function SearchOnlineMods(arg1) {
  return window['go']['app']['App']['SearchOnlineMods'](arg1);
}

export function SelectUncivDir() {
  return window['go']['app']['App']['SelectUncivDir']();
}

export function SetUncivPath(arg1) {
  return window['go']['app']['App']['SetUncivPath'](arg1);
}

export function SetZoomLevel(arg1) {
  return window['go']['app']['App']['SetZoomLevel'](arg1);
}

export function StartDownload(arg1, arg2) {
  return window['go']['app']['App']['StartDownload'](arg1, arg2);
}

export function StartDownloadWithMirror(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartDownloadWithMirror'](arg1, arg2, arg3);
}

export function TestMirrorsLatency() {
  return window['go']['app']['App']['TestMirrorsLatency']();
}

export function TranslateText(arg1) {
  return window['go']['app']['App']['TranslateText'](arg1);
}

export function ValidateDownloadURL(arg1) {
  return window['go']['app']['App']['ValidateDownloadURL'](arg1);
}

export function ValidateUncivPath(arg1) {
  return window['go']['app']['App']['ValidateUncivPath'](arg1);
}
