// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListDocs():Promise<Array<main.DocInfo>>;

export function ReadDoc(arg1:string):Promise<string>;
