// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListDocs() {
  return window['go']['main']['DocReader']['ListDocs']();
}

export function ReadDoc(arg1) {
  return window['go']['main']['DocReader']['ReadDoc'](arg1);
}
